-- A-02: rulesets por nivel para HipertrofiaV2 (Intermedio, Avanzado).
-- Antes los tres niveles usaban hipertrofia_v2_principiante. Derivados del
-- de principiante subiendo volumen (series), RIR objetivo, intensidad y
-- adelantando el deload. Idempotente: reemplaza si ya existen.

DELETE FROM app.mindfeed_rulesets WHERE scope IN ('hipertrofia_v2_intermedio','hipertrofia_v2_avanzado');

INSERT INTO app.mindfeed_rulesets (scope, version, rules, is_active) VALUES ('hipertrofia_v2_intermedio', 'mindfeed_spec_v1', '{"meta":{"spec":"MindFeed_Compliance_Spec_v1","level":"Intermedio"},"deloadRules":{"loadFactor":0.7,"deloadWeeks":[5],"volumeFactor":0.5,"reactiveWindowDays":10,"plannedTriggerMicrocycles":5,"reactiveCriticalFlagsThreshold":1},"overlapRules":{"windowHours":72,"highAdjustmentFactor":0.95,"partialAdjustmentFactor":0.975},"priorityRules":{"topSet":{"maxPercent":85,"minMeanRir":3,"weeklyLimit":1,"initialPercent":82.5,"firstWeeksLimit":4,"minWeeksForMaxPercent":2},"nonPriority":{"heavyDayRange":[75,77.5],"heavyDayPercent":76,"lightDayPercent":70,"progressionFrozen":true,"reactivationWeeks":2,"reactivationMeanRir":4},"priorityProgression":{"baseIncrementPct":2.5,"lowMeanRirThreshold":2,"highMeanRirThreshold":3,"lowReadinessDecrementPct":-2.5,"highReadinessIncrementPct":3.5}},"intensityByDay":{"lightDaysRange":[72,77],"heavyDaysPercent":82.5},"volumeProfiles":{"Core":{"sets":3,"analitico":3,"unilateral":0,"multiarticular":0},"Pecho":{"sets":3,"analitico":1,"unilateral":1,"multiarticular":1},"Hombro":{"sets":3,"analitico":1,"unilateral":0,"multiarticular":1},"Bíceps":{"sets":3,"analitico":1,"unilateral":1,"multiarticular":0},"Espalda":{"sets":3,"analitico":1,"unilateral":1,"multiarticular":1},"Gemelos":{"sets":3,"analitico":1,"unilateral":0,"multiarticular":0},"Glúteo":{"sets":3,"analitico":0,"unilateral":1,"multiarticular":0},"Tríceps":{"sets":3,"analitico":1,"unilateral":1,"multiarticular":0},"Hombro (medios)":{"sets":3,"analitico":1,"unilateral":0,"multiarticular":0},"Piernas (isquios)":{"sets":3,"analitico":0,"unilateral":1,"multiarticular":1},"Hombro (posterior)":{"sets":3,"analitico":1,"unilateral":0,"multiarticular":0},"Piernas (cuádriceps)":{"sets":3,"analitico":0,"unilateral":1,"multiarticular":2}},"restSecondsByType":{"analitico":50,"unilateral":60,"multiarticular":90},"rirTarget":"1-2"}'::jsonb, TRUE);
INSERT INTO app.mindfeed_rulesets (scope, version, rules, is_active) VALUES ('hipertrofia_v2_avanzado', 'mindfeed_spec_v1', '{"meta":{"spec":"MindFeed_Compliance_Spec_v1","level":"Avanzado"},"deloadRules":{"loadFactor":0.7,"deloadWeeks":[5],"volumeFactor":0.5,"reactiveWindowDays":10,"plannedTriggerMicrocycles":5,"reactiveCriticalFlagsThreshold":1},"overlapRules":{"windowHours":72,"highAdjustmentFactor":0.95,"partialAdjustmentFactor":0.975},"priorityRules":{"topSet":{"maxPercent":85,"minMeanRir":3,"weeklyLimit":1,"initialPercent":82.5,"firstWeeksLimit":4,"minWeeksForMaxPercent":2},"nonPriority":{"heavyDayRange":[75,77.5],"heavyDayPercent":76,"lightDayPercent":70,"progressionFrozen":true,"reactivationWeeks":2,"reactivationMeanRir":4},"priorityProgression":{"baseIncrementPct":2.5,"lowMeanRirThreshold":2,"highMeanRirThreshold":3,"lowReadinessDecrementPct":-2.5,"highReadinessIncrementPct":3.5}},"intensityByDay":{"lightDaysRange":[75,80],"heavyDaysPercent":85},"volumeProfiles":{"Core":{"sets":4,"analitico":3,"unilateral":0,"multiarticular":0},"Pecho":{"sets":4,"analitico":2,"unilateral":1,"multiarticular":1},"Hombro":{"sets":4,"analitico":2,"unilateral":0,"multiarticular":1},"Bíceps":{"sets":4,"analitico":2,"unilateral":1,"multiarticular":0},"Espalda":{"sets":4,"analitico":2,"unilateral":1,"multiarticular":1},"Gemelos":{"sets":4,"analitico":1,"unilateral":0,"multiarticular":0},"Glúteo":{"sets":4,"analitico":0,"unilateral":1,"multiarticular":0},"Tríceps":{"sets":4,"analitico":2,"unilateral":1,"multiarticular":0},"Hombro (medios)":{"sets":4,"analitico":1,"unilateral":0,"multiarticular":0},"Piernas (isquios)":{"sets":4,"analitico":0,"unilateral":1,"multiarticular":1},"Hombro (posterior)":{"sets":4,"analitico":1,"unilateral":0,"multiarticular":0},"Piernas (cuádriceps)":{"sets":4,"analitico":0,"unilateral":1,"multiarticular":2}},"restSecondsByType":{"analitico":50,"unilateral":60,"multiarticular":90},"rirTarget":"0-2"}'::jsonb, TRUE);
